site:
  title: Rancher
  url: /
  start_page: latest@rancher:en:introduction.adoc
  robots: disallow
content:
  sources: 
  - url: .
    branches: [main]
    start_paths: [versions/latest, versions/v2.9, versions/v2.8]
ui: 
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files
asciidoc:
  attributes:
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
  - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en, zh]
